- name: Restart Docker service
  service:
    name: docker
    state: restarted
  when: docker_service_changed

- name: Reload Docker service
  systemd:
    name: docker
    state: reloaded
  when: docker_service_changed