- name: Ensure docker group exists
  group:
    name: docker
    state: present
  become: true

- name: Install dependencies for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present
    update_cache: yes
  become: true

- name: Remove old Docker versions if exist
  apt:
    name:
      - docker
      - docker.io
      - docker-engine
      - containerd
    state: absent
    purge: yes
  become: true
  ignore_errors: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  become: true

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: true

- name: Stop docker.socket temporarily
  service:
    name: docker.socket
    state: stopped
  become: true

- name: Remove existing docker socket file
  file:
    path: /var/run/docker.sock
    state: absent
  become: true
  ignore_errors: yes

- name: Ensure containerd service is running
  service:
    name: containerd
    state: started
    enabled: true
  become: true

- name: Verify docker group exists before starting socket
  command: getent group docker
  register: docker_group_check
  changed_when: false
  become: true

- name: Start docker.socket
  service:
    name: docker.socket
    state: started
    enabled: true
  become: true
  when: docker_group_check.rc == 0

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Verify docker socket exists
  stat:
    path: /var/run/docker.sock
  register: docker_sock

- name: Debug socket permissions
  debug:
    msg: "Docker socket exists with permissions {{ docker_sock.stat.mode }}"
  when: docker_sock.stat.exists

- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Reset connection to apply group changes
  meta: reset_connection